SCHEMA_DISPAROS_WPP = {
    "celular": {"nomes_origem": ["Celular"], "data_type": "string"},
    "conta": {"nomes_origem": ["Conta"], "data_type": "string"},
    "nome": {"nomes_origem": ["Nome"], "data_type": "string"},
    "status": {"nomes_origem": ["Status"], "data_type": "string"},
    "template": {"nomes_origem": ["Template"], "data_type": "string"},
    "nvar": {"nomes_origem": ["nVar"], "data_type": "string"},
    "enviado": {"nomes_origem": ["Enviado"], "data_type": "string"},
    "var1": {"nomes_origem": ["var1"], "data_type": "string"},
    "var2": {"nomes_origem": ["var2"], "data_type": "string"},
    "var3": {"nomes_origem": ["var3"], "data_type": "string"},
    "var4": {"nomes_origem": ["var4"], "data_type": "string"},
    "var5": {"nomes_origem": ["var5"], "data_type": "string"},
    "var6": {"nomes_origem": ["var6"], "data_type": "string"},
    "var7": {"nomes_origem": ["var7"], "data_type": "string"},
    "var8": {"nomes_origem": ["var8"], "data_type": "string"},
    "var9": {"nomes_origem": ["var9"], "data_type": "string"},
    "data_envio": {"nomes_origem": ["Data_envio"], "data_type": "timestamp[us]"},
    "msg_id": {"nomes_origem": ["MSG_ID"], "data_type": "string"},
    "fila": {"nomes_origem": ["Fila"], "data_type": "string"},
    "mensagem": {"nomes_origem": ["Mensagem"], "data_type": "string"},
    "classificacao_ai": {"nomes_origem": ["Classificacao_AI"], "data_type": "string"},
    "data_interacao": {"nomes_origem": ["Data_interacao"], "data_type": "string"},
    "data_visualizacao": {"nomes_origem": ["Data_visualizacao"], "data_type": "string"},
    "campaign_id": {"nomes_origem": ["Campaign_ID"], "data_type": "string"},
}

SCHEMA_DISPAROS_WPP_SILVER = {
    "celular": {"nomes_origem": ["Celular"], "data_type": "string"},
    "conta": {"nomes_origem": ["Conta"], "data_type": "string"},
    "nome": {"nomes_origem": ["Nome"], "data_type": "string"},
    "status": {"nomes_origem": ["Status"], "data_type": "string"},
    "template": {"nomes_origem": ["Template"], "data_type": "string"},
    "nvar": {"nomes_origem": ["nVar"], "data_type": "string"},
    "enviado": {"nomes_origem": ["Enviado"], "data_type": "string"},
    "var1": {"nomes_origem": ["var1"], "data_type": "string"},
    "var2": {"nomes_origem": ["var2"], "data_type": "string"},
    "var3": {"nomes_origem": ["var3"], "data_type": "string"},
    "var4": {"nomes_origem": ["var4"], "data_type": "string"},
    "var5": {"nomes_origem": ["var5"], "data_type": "string"},
    "var6": {"nomes_origem": ["var6"], "data_type": "string"},
    "var7": {"nomes_origem": ["var7"], "data_type": "string"},
    "var8": {"nomes_origem": ["var8"], "data_type": "string"},
    "var9": {"nomes_origem": ["var9"], "data_type": "string"},
    "data_envio": {"nomes_origem": ["Data_envio"], "data_type": "timestamp[us]"},
    "msg_id": {"nomes_origem": ["MSG_ID"], "data_type": "string"},
    "fila": {"nomes_origem": ["Fila"], "data_type": "string"},
    "mensagem": {"nomes_origem": ["Mensagem"], "data_type": "string"},
    "classificacao_ai": {"nomes_origem": ["Classificacao_AI"], "data_type": "string"},
    "data_interacao": {"nomes_origem": ["Data_interacao"], "data_type": "string"},
    "data_visualizacao": {"nomes_origem": ["Data_visualizacao"], "data_type": "string"},
    "campaign_id": {"nomes_origem": ["Campaign_ID"], "data_type": "string"},
    "ano_particao": {"nomes_origem": ["ano_particao"], "data_type": "int64"},
    "mes_particao": {"nomes_origem": ["mes_particao"], "data_type": "int64"},
}

SCHEMA_TEMPLATES_RECEITA = {
    "template": {"nomes_origem": ["Template"], "data_type": "string"},
    "data": {"nomes_origem": ["Data"], "data_type": "timestamp[us]"},
    "tipo": {"nomes_origem": ["Tipo"], "data_type": "string"},
    "tempo_apos": {"nomes_origem": ["Tempo após"], "data_type": "float"},
    "quantidade": {"nomes_origem": ["Quantidade"], "data_type": "int64"},
    "custo_estimado": {"nomes_origem": ["Custo_estimado"], "data_type": "float"},
    "receita": {"nomes_origem": ["Receita"], "data_type": "float"},
    "categoria": {"nomes_origem": ["Categoria"], "data_type": "string"},
    "produto_1": {"nomes_origem": ["Produto_1"], "data_type": "string"},
    "multirao": {"nomes_origem": ["Multirão"], "data_type": "string"},
    "produto_2": {"nomes_origem": ["Produto_2"], "data_type": "string"},
}

SCHEMA_TEMPLATES_RECEITA_SILVER = {
    "template": {"nomes_origem": ["Template"], "data_type": "string"},
    "data": {"nomes_origem": ["Data"], "data_type": "timestamp[us]"},
    "tipo": {"nomes_origem": ["Tipo"], "data_type": "string"},
    "tempo_apos": {"nomes_origem": ["Tempo após"], "data_type": "float"},
    "quantidade": {"nomes_origem": ["Quantidade"], "data_type": "int64"},
    "custo_estimado": {"nomes_origem": ["Custo_estimado"], "data_type": "float"},
    "receita": {"nomes_origem": ["Receita"], "data_type": "float"},
    "categoria": {"nomes_origem": ["Categoria"], "data_type": "string"},
    "produto_1": {"nomes_origem": ["Produto_1"], "data_type": "string"},
    "multirao": {"nomes_origem": ["Multirão"], "data_type": "string"},
    "produto_2": {"nomes_origem": ["Produto_2"], "data_type": "string"},
    "ano_particao": {"nomes_origem": ["ano_particao"], "data_type": "int64"},
    "mes_particao": {"nomes_origem": ["mes_particao"], "data_type": "int64"},
}
