name: CI Test

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test pyflakes
        runs-on: ubuntu-latest
        
        steps: 
            - name: Instala pyflakes
              run: pip install pyflakes
              
            - name: Executar teste Pyflakes
              run: pyflakes check ./
